### Plot Options
```{r}
checkboxInput("plotlines", "Plot lines", value = TRUE)
checkboxInput("plotevents", "Plot foot events", value = TRUE)

selectizeInput("participant3d", "Participant",
  choices = participants, selected = participants[1], multiple = FALSE)
selectizeInput("trialNum3d", "Trial Number",
  choices = trials, selected = trials[1], multiple = FALSE)

numericInput("startTime", "Start time (s)",
  min = 0, max = 500, value = 0, step = 1)
numericInput("endTime", "End time (s)",
  min = 0, max = 500, value = 0, step = 1)
checkboxInput("doFilter_3d", "Filter data", value = FALSE)

numericInput("maxv", "Max velocity for filtering (m/s)",
  min = 0, value = 10, step = 1)
  numericInput("maxvrot", "Max rotational velocity for filtering (radians/s)",
  min = 0, value = 3, step = 1)
numericInput("nPasses", "Number of filter passes",
  min = 1, max = 10, value = 1, step = 1)

# Add a download button for the plot
downloadButton("download3dPlot", "Download Plot")
```

Column
--------------------------------------------
### 3D plot {data-height=1500}

```{r}
rglwidgetOutput("ThreeD", width = "100%", height = "800px")
```

```{r, context="server"}
tf_gizmo <- function(origin, len, rotationMatrix = diag(4), label = "", labelaxes = TRUE, labelsize = 0.6){
  rotationMatrix <- rotationMatrix[1:3,1:3] # we only use the rotation
  xAxis <- as.vector(rotationMatrix %*% c(len, 0, 0))
  yAxis <- as.vector(rotationMatrix %*% c(0, len, 0))
  zAxis <- as.vector(rotationMatrix %*% c(0, 0, len))
  arrow3d(origin, origin + xAxis, col="red")   # X-axis
  arrow3d(origin, origin + yAxis, col="green") # Y-axis
  arrow3d(origin, origin + zAxis, col="blue")  # Z-axis
  
  text3d(origin, text = label, col = "white", adj = c(0, 0), cex = labelsize)
  
  # Label the axes
  if (labelaxes) {
    text3d(origin + xAxis, text = "X", col = "red", adj = c(0, 0), cex = 0.5*labelsize)
    text3d(origin + yAxis, text = "Y", col = "green", adj = c(0, 0), cex = 0.5*labelsize)
    text3d(origin + zAxis, text = "Z", col = "blue", adj = c(0, 0), cex = 0.5*labelsize)
  }
}

draw_mean_axes <- function(data, trackerName, label, labelsize = 0.6){
  posCols <- grep(paste0(trackerName,"\\.pos"), colnames(data), value = TRUE)
  rotCols <- grep(paste0(trackerName,"\\.rot"), colnames(data), value = TRUE)
  
  # Calculate the means (First 1000 datapoints should suffice, is just for plot)
  medPos <- sapply(data[1:1000, posCols], median, na.rm = TRUE)
  meanQuaternion <- sapply(data[1:1000, rotCols], median, na.rm = TRUE) # this should be done with slerp but for now this is fine.
  
  points3d(medPos[1], medPos[2], medPos[3], col = "red", size = 5)
  tf_gizmo(medPos, 0.1, quaternion_to_rotation_matrix(meanQuaternion), label, labelsize)
}

output$ThreeD <- renderPlaywidget({
  # Clear existing rgl plot
  clear3d()
  # Set uniform aspect ratio
  rgl::aspect3d(1, 1, 1)
  # Get data
  data <- preprocess_data(input$participant3d, as.numeric(input$trialNum3d))
  if (input$doFilter_3d) {
    data <- filter_all_data(data, input$maxv, input$maxvrot, input$nPasses)
  }
  
  # Subset data based on start and end times
  #data <- subset(data, time >= input$startTime & time <= input$endTime)
  
  # Add axes
  axes3d()
  axis3d('y', pos = c(0, 0, 0))
  
  # Plot transformation data
  # Add origin arrows
  tf_gizmo(c(0,0,0), 0.2)
  
  # Create your 3D plot
  leftFootCols <- grep("LeftFoot.pos", colnames(data), value = TRUE)
  rightFootCols <- grep("RightFoot.pos", colnames(data), value = TRUE)
  
  if (input$plotlines) {
    lines3d(data[[leftFootCols[1]]], data[[leftFootCols[2]]], data[[leftFootCols[3]]], color="black") 
    lines3d(data[[rightFootCols[1]]], data[[rightFootCols[2]]], data[[rightFootCols[3]]], color="black") 
  }
  
  if (input$plotevents) {
    # Add gait events
    gaitParams <- filteredParams()  # Assuming this function provides the gait parameters
    gaitParams <- gaitParams[gaitParams$participant == input$participant3d & gaitParams$trialNum == input$trialNum3d, ]
    
    rParams <- gaitParams[gaitParams$heelStrikes.foot == "Right", ]
    lParams <- gaitParams[gaitParams$heelStrikes.foot == "Left", ]
    
    # Plot heel strikes
    points3d(rParams$heelStrikes.pos.x, rParams$heelStrikes.pos.y, rParams$heelStrikes.pos.z, color = "red", size = 5)
    points3d(lParams$heelStrikes.pos.x, lParams$heelStrikes.pos.y, lParams$heelStrikes.pos.z, color = "blue", size = 5)
  }
  
  draw_mean_axes(data, "TreadmillLeft", "L", 1)
  draw_mean_axes(data, "TreadmillRight", "R", 1)
  
  # Return the rgl widget
  rglwidget()
})

# Add a download handler for the plot
output$download3dPlot <- downloadHandler(
  filename = function() {
    paste("3D_plot", Sys.pos.Date(), ".png", sep = "")
  },
  content = function(file) {
    # Capture the current 3D plot
    rgl.snapshot(file, fmt = "png")
  }
)

#plotGaitData <- function(result) {
#  # Clear existing rgl plot
#  clear3d()
#  rgl::aspect3d(1, 1, 1) # Set uniform aspect ratio
#  # Add axes
#  axes3d()
#  axis3d('y', pos = c(0, 0, 0))
#  # Add origin arrows
#  tfGizmo(c(0,0,0), 0.2)
#  
#  # Assign data variables
#  data <- result$data
#  gaitMetrics <- result$gaitMetrics
#  
#  # Left foot position columns
#  posColsLeft <- grep("LeftFoot.pos", colnames(data), value = TRUE)
#  xColLeft <- grep("x", posColsLeft, value = TRUE)
#  yColLeft <- grep("y", posColsLeft, value = TRUE)
#  zColLeft <- grep("z", posColsLeft, value = TRUE)
#  
#  # Right foot position columns
#  posColsRight <- grep("RightFoot.pos", colnames(data), value = TRUE)
#  xColRight <- grep("x", posColsRight, value = TRUE)
#  yColRight <- grep("y", posColsRight, value = TRUE)
#  zColRight <- grep("z", posColsRight, value = TRUE)
#  
#  # Plot left foot trajectory
#  lines3d(data[[xColLeft]], data[[yColLeft]], data[[zColLeft]], color="black") # left
#  lines3d(data[[xColRight]], data[[yColRight]], data[[zColRight]], color="black") # right 
#  
#  # Plot left foot heel strikes and toe-offs
#  points3d(gaitMetrics[gaitMetrics$Foot=="Left",]$HeelStrikeX, gaitMetrics[gaitMetrics$Foot=="Left",]$HeelStrikeY, gaitMetrics[gaitMetrics$Foot=="Left",]$HeelStrikeZ, color="blue", size=5)
#  points3d(gaitMetrics[gaitMetrics$Foot=="Left",]$ToeOffX, gaitMetrics[gaitMetrics$Foot=="Left",]$ToeOffY, gaitMetrics[gaitMetrics$Foot=="Left",]$ToeOffZ, color="green", size=5)
#  
#  # Plot right foot heel strikes and toe-offs
#  points3d(gaitMetrics[gaitMetrics$Foot=="Right",]$HeelStrikeX, gaitMetrics[gaitMetrics$Foot=="Right",]$HeelStrikeY, gaitMetrics[gaitMetrics$Foot=="Right",]$HeelStrikeZ, color="red", size=5)
#  points3d(gaitMetrics[gaitMetrics$Foot=="Right",]$ToeOffX, gaitMetrics[gaitMetrics$Foot=="Right",]$ToeOffY, gaitMetrics[gaitMetrics$Foot=="Right",]$ToeOffZ, color="yellow", size=5)
#  
#  # Draw treadmill positions
#  drawMeanAxes(data, "TreadmillLeft", "L", 1)
#  drawMeanAxes(data, "TreadmillRight","R", 1)
#  
#  # Return the rgl widget
#  rglwidget(width = "1200px", height = "600px")
#}
```
