### Options

```{r}
selectizeInput("plotVar", "Variable", choices = muVars, selected = "stepWidths.sd", multiple = FALSE)
#selectizeInput("plotMetric", "Metric", choices = varMetrics, selected = varMetrics[1], multiple = FALSE)
selectizeInput("varCategory", "Category", choices = categoriesExtraInputs, selected = "VFD", multiple = TRUE)
selectizeInput("colorCategory", "Color", choices = categoriesExtraInputs, selected = "None", multiple = FALSE)
selectizeInput("shapeCategory", "Shape", choices = categoriesExtraInputs, selected = "None", multiple = FALSE)
checkboxInput("doPaired", "Make it a paired plot",value=FALSE)
selectizeInput("pairedCategory", "Paired Category", choices = categoriesExtraInputs, selected = "None", multiple = FALSE)
```

Column
--------------------------------------------

### Step Variability Plot  {data-height=2500}
Generate boxplots of the selected data that are split up according to different categories.
```{r}
imageOutput("var")
```

```{r, context="server"}
# Reactive for dynamic data (shared across multiple operations)
mu_data <- reactive({
  get_mu_dyn_long()
})

# Update selectizeInput choices only when `mu_data` changes
observeEvent(mu_data(), {
  cols <- colnames(mu_data())
  updateSelectizeInput(session, "plotVar", choices = cols, selected = "stepWidths.sd")
})

output$var <- renderSVG({ reactive({
  mu <- mu_data()
    if (!input$doPaired) {
      plot_boxplots(mu, input$plotVar, input$varCategory, input$colorCategory, input$shapeCategory, input$baseSize)
    }
    else {
      plot_paired(mu, input$plotVar, input$pairedCategory, input$varCategory, input$colorCategory, input$shapeCategory, input$baseSize)
    }
  })
})
```