
### Plot Options
```{r}
checkboxInput("plotlines", "plot lines",value=TRUE)
checkboxInput("plotpoints", "plot points",value=FALSE)

selectizeInput("xtracker", "Data to plot",
  choices = trackers, selected = trackers[2], multiple = FALSE)
#selectizeInput("ytracker", "Y Data to plot",
#  choices = trackers, selected = trackers[2], multiple = FALSE)

selectizeInput("participant2d", "participant",
  choices = participants, selected = participants[1], multiple = FALSE)
selectizeInput("trialNum2d", "Trial Number",
  choices = trials, selected = trials[1], multiple = FALSE)


selectizeInput("xplot2d", "xplot",
  choices = xOptions2D, selected = xOptions2D[2], multiple = FALSE)
selectizeInput("yplot2d", "yplot",
  choices = xOptions2D, selected = xOptions2D[3], multiple = FALSE)

numericInput("startTime", "start time (s)",
  min = 0, max = 500, value = 0, step = 1)
numericInput("endTime", "end time (s)",
  min = 0, max = 500, value = 0, step = 1)

# Add a download button for the plot
downloadButton("download2dPlot", "Download Plot")
```


Column
--------------------------------------------
### 2D plot {data-height=1500}

```{r}
imageOutput("TwoD")
```

```{r, context="server"}
observeEvent(input$xtracker, {
  choices <- getOptions(input$xtracker)
  updateSelectInput(session= getDefaultReactiveDomain(),"xplot2d", choices = choices, selected = choices[1])
  updateSelectInput(session= getDefaultReactiveDomain(),"yplot2d", choices = choices, selected = choices[1])
})

output$TwoD <- renderSVG({ reactive({
  # note, 2 times xtracker, not distinguishing between x and y for now.
    plot_2d(input$xtracker, input$xtracker, input$participant2d, as.numeric(input$trialNum2d), input$startTime, input$endTime, input$xplot2d, input$yplot2d, input$plotlines, input$plotpoints, baseSize=input$baseSize)
  })}
)

# Add a download handler for the plot
output$download2dPlot <- downloadHandler(
  filename = function() {
    paste("2D_plot", Sys.Date(), ".svg", sep = "")
  },
  content = function(file) {
    ggsave(file, plot = plot_2d(input$xtracker, input$xtracker, input$participant2d, as.numeric(input$trialNum2d), input$startTime, input$endTime, input$xplot2d, input$yplot2d, input$plotlines, input$plotpoints, baseSize = input$baseSize), device = "svg")
  }
)
```
