
### Plot Options
```{r}
checkboxInput("plotlines", "plot lines",value=TRUE)
checkboxInput("plotpoints", "plot points",value=FALSE)

selectizeInput("xtracker", "Data to plot",
  choices = trackers, selected = trackers[2], multiple = FALSE)

selectizeInput("participant2d", "participant",
  choices = participants, selected = participants[1], multiple = FALSE)
selectizeInput("trialNum2d", "Trial Number",
  choices = trialNumbers, selected = trialNumbers[2], multiple = FALSE)


selectizeInput("xplot2d", "xplot",
  choices = xOptions2D, selected = xOptions2D[2], multiple = FALSE)
selectizeInput("yplot2d", "yplot",
  choices = xOptions2D, selected = xOptions2D[3], multiple = FALSE)
```


Column
--------------------------------------------
### 2D plot {data-height=1500}
Simple interface to create some 2D plots of the raw tracker data for debugging purposes.
```{r}
#imageOutput("TwoD")
plotlyOutput("TwoD_interactive")
```

```{r, context="server"}
observeEvent(input$xtracker, {
  choices <- getOptions(input$xtracker)
  updateSelectInput(session= getDefaultReactiveDomain(),"xplot2d", choices = choices, selected = choices[2])
  updateSelectInput(session= getDefaultReactiveDomain(),"yplot2d", choices = choices, selected = choices[3])
})

output$TwoD <- renderSVG({ reactive({
  # note, 2 times xtracker, not distinguishing between x and y for now.
    plot_2d(input$xtracker, input$xtracker, input$participant2d, as.numeric(input$trialNum2d), input$xplot2d, input$yplot2d, input$plotlines, input$plotpoints, baseSize=input$baseSize)
  })}
)


output$TwoD_interactive <- renderPlotly({
  p <- plot_2d(
    input$xtracker, input$xtracker, 
    input$participant2d, 
    as.numeric(input$trialNum2d), 
    input$xplot2d, input$yplot2d, 
    input$plotlines, input$plotpoints, 
    baseSize=input$baseSize
  )

  # Convert to ggplotly
  ggplotly(p, width = input$plotwidth, height = input$plotheight) %>% layout(autosize = F)
})
```
