---
title: "Participant Report"
output: pdf_document
params:
  traj_plots_z: NA
  traj_plots_y: NA
  traj_plots_x: NA
  pie_charts: NA
  questionnaire_plots: NA
  variability_plots: NA
  target_stepping_plot: NA
  scatter_plot: NA
---

```{r setup, include=FALSE}
library(gridExtra)
library(grid)

# Access parameters
traj_plots_z <- params$traj_plots_z
traj_plots_y <- params$traj_plots_y
traj_plots_x <- params$traj_plots_x
pie_charts <- params$pie_charts
questionnaire_plots <- params$questionnaire_plots
variability_plots <- params$variability_plots
target_stepping_plot <- params$target_stepping_plot
scatter_plot <- params$scatter_plot
```

### Page 1: Foot Trajectories and Pie Charts
```{r, fig.width = 8.3, fig.height = 11.7}
# Combine all foot trajectory plots
foot_trajectories <- c(traj_plots_z, traj_plots_y, traj_plots_x)

# Arrange Foot Trajectories and Pie Charts
grid.arrange(
  grobs = list(
    arrangeGrob(grobs = foot_trajectories, ncol = 2),
    arrangeGrob(grobs = pie_charts, ncol = 4, width = c(1,1,1,1.4) )
  ),
  ncol = 1,
  heights = c(3, 1)
)
```

### Page 2: Variability Plots, Scatter Plot, and Target Stepping Plot
```{r, fig.width = 8.3, fig.height = 11.7}
# Combine variability plots with scatter plot and target stepping plot
all_plots <- list(scatter_plot, target_stepping_plot)

# Arrange Variability Plots, Scatter Plot, and Target Stepping Plot
grid.arrange(
  grobs = list(
    arrangeGrob(grobs = all_plots, ncol = 2, widths = c(1.5,1)),
    arrangeGrob(grobs = variability_plots, ncol = 2)
  ),
  ncol = 1
)
```

### Page 3: Questionnaire Results
```{r, fig.width = 8.3, fig.height = 11.7}
# Arrange Questionnaire Results
grid.arrange(
  grobs = questionnaire_plots,
  ncol = 1,
  heights = c(1, 1, 1)  # Adjust height ratios if needed
)
```
