---
title: "VFD for gait variability"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll # scroll # fill
runtime: shinyrmd
---

```{r setup, include=FALSE}
#cache=TRUE, local=FALSE
source('source/setup.R')
source('source/dataloading.R', local = FALSE)

source('source/find_foot_events.R', local = FALSE)
# Column definitions
xOptions <- c("time", "pos_x", "pos_y", "pos_z")
#xOptionsVFD <- c("time", "magnitude", "offset_x", "offset_y", "offset_z", "final_pos_x", "final_pos_y", "final_pos_z", "rel_pos_x", "rel_pos_y", "rel_pos_z")
xOptions2D <- colnames(get_t_data(participants[1],"leftfoot",1)) # options for pos rot trackers

## Gait params
source('source/calc_all_gait_params.R', local = FALSE)
# Check if the files already exist
resultsFolder <- "results" 
agpFile <- file.path(resultsFolder, "allGaitParams.rds")
atpFile <- file.path(resultsFolder, "allTargetParams.rds")
aqrFile <- file.path(resultsFolder, "allQResults.rds")
if (file.exists(agpFile) && file.exists(atpFile) && file.exists(aqrFile)) {
  # Load the existing tables from the files
  allQResults <- readRDS(aqrFile)
  allGaitParams <- readRDS(agpFile)
  allTargetParams <- readRDS(atpFile)
} else {
  # Calculate the tables and save them to files
  allQResults <- get_all_questionnaire_results()
  allGaitParams <- calc_all_gait_params()
  allTargetParams <- calc_all_target_params()
  saveRDS(allQResults, aqrFile)
  saveRDS(allGaitParams, agpFile)
  saveRDS(allTargetParams, atpFile)
}

dataTypes         <- setdiff(getTypes(allGaitParams), categories)
dataTypesTargets  <- setdiff(getTypes(allTargetParams), categories)

## Summary tables
source('source/summaryparams.R', local = FALSE)
mu <- get_full_mu(allGaitParams, allQResults, dataTypes, categories)
muDataTypes <- setdiff(getTypes(mu), categories)

## Plotting code
source('source/plotting.R', local = FALSE)
```


Sidebar {.sidebar}
=====================================
```{r, child='pages/sidebar_dynamicDataFiltering.Rmd'}
```

```{r, context="server", local=FALSE}
source('source/get_filtered_data.R', local = TRUE)
```



Feet trajectories {data-orientation=columns}
=====================================
```{r, child='pages/page1_feetTrajectories.Rmd'}
```

Removed Steps
=====================================
```{r, child='pages/page2_removedSteps.Rmd'}
```


2D Plot {data-orientation=columns}
=====================================
```{r, child='pages/page3_twoDPlot.Rmd'}
```


Target Steps
=====================================
```{r, child='pages/page4_targetSteps.Rmd'}
```


Histograms 
=====================================
```{r, child='pages/page5_histograms.Rmd'}
```


Scatterplots
=====================================
```{r, child='pages/page6_scatterplots.Rmd'}
```


Scatterplots TrialData
=====================================
```{r, child='pages/page7_trialScatterplots.Rmd'}
```


Questionnaires 
=====================================
```{r, child='pages/page8_questionnaires.Rmd'}
```


Variability 
=====================================
```{r, child='pages/page9_variability.Rmd'}
```


Statistics {data-icon="fa-chart-bar"}
=====================================
```{r, child='pages/page10_statistics.Rmd'}
```


Correlations {data-icon="fa-chart-line"}
=====================================
```{r, child='pages/page11_correlations.Rmd'}
```


Participant Summary {data-icon="fa-id-card-clip"}
=====================================
```{r, child='pages/page12_participantSummary.Rmd'}
```


Data Table {data-icon="fa-table"}
=====================================
```{r, child='pages/page13_table.Rmd'}
```
